### ISSUE TITLE
iPhoneX SafeAreaView support on createMaterialTopNavigator

### ISSUE THREAD

**Issue by fabriziogiordano** [react-navigation/react-navigation-tabs#1]
### Current behaviour

`createMaterialTopTabNavigator` nor `createBottomTabNavigator` handle iPhoneX.

### Expected behaviour

`createMaterialTopTabNavigator` or `createBottomTabNavigator` handle iPhoneX.

### Code sample

Here the Snack:
https://snack.expo.io/@fabrygio/react-navigator-2.x-beta-3---top-bottom-nav

### Screenshots (if applicable)
<img width="420" alt="screen shot 2018-03-20 at 7 29 06 pm" src="https://user-images.githubusercontent.com/109390/37688153-faa5f3f4-2c74-11e8-912c-f7c1158ea423.png">

<img width="420" alt="screen shot 2018-03-20 at 7 29 04 pm" src="https://user-images.githubusercontent.com/109390/37688154-fab13b92-2c74-11e8-820f-4516990054f7.png">

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |
| react-native          |
| react-navigation-tabs |
| node                  |
| npm or yarn           |

**Comment by satya164** [comment]
FYI you can use the `tabBarComponent` option to wrap it in a `SafeArea`.

**Comment by alburdette619** [comment]
@satya164 Can you give an example?

**Comment by brentvatne** [comment]
https://github.com/react-navigation/react-navigation/blob/1951a3ac4629f9dbba444c2ced63a46ab4ee4165/examples/NavigationPlayground/js/StacksOverTopTabs.js#L107

**Comment by brentvatne** [comment]
maybe we should leave this open actually as it might be nice to handle automatically

**Comment by tonygentilcore** [comment]
Regarding @satya164 claim that no apps use this pattern, Instagram does it on their activity tab and I'd like something similar in my app.

Regarding @zenggang97's suggested workaround, this is dangerous because it misses other current notched iPhones (RN's SafeAreaView also handles XR and XMax) as well as future devices.

For others looking for a quick workaround, I ended up with:
```jsx
import React from 'react'
import { SafeAreaView } from 'react-native'
import { createMaterialTopTabNavigator, MaterialTopTabBar } from 'react-navigation'


function SafeAreaMaterialTopTabBar (props) {
  return (
    <SafeAreaView>
      <MaterialTopTabBar {...props} />
    </SafeAreaView>
  )
}

const MyNav = createMaterialTopTabNavigator({
  ...
}, {
  ...
  tabBarComponent: SafeAreaMaterialTopTabBar
})
```

**Comment by satya164** [comment]
> Regarding @satya164 claim that no apps use this pattern, Instagram does it on their activity tab and I'd like something similar in my app.

I didn't claim that no app uses this pattern. I said it's not a common pattern and I haven't seen it used.

Anyway, we can't add it in the library by default because in the common case people wouldn't want it. And when you need it, it's very straightforward to wrap the default tab bar in a safeareaview. I'm closing this issue since it's not actionable.

**Comment by brentvatne** [comment]
ideally we can handle this better in the future when there are better primitives in place, like i mentioned in https://github.com/react-navigation/react-navigation-tabs/issues/1#issuecomment-402546663 -- it's unfortunately taking a while and if someone wants to jump into the pr i referenced there to help out, please do!
