### ISSUE TITLE
tabBarVisible is ignored for nested scenes

### ISSUE THREAD

**Issue by AndrewIngram** [react-navigation/react-navigation-tabs#18]
With react-navigation before 2.0, setting `tabBarVisible: false` at any level in the navigation tree would cause the tab bar to be hidden, this behaviour is now broken.

### Current behaviour

Setting `tabBarVisible: false` on any scene below the top level tab scenes will have no effect, making the setting largely useless because the top-level is probably the place where you can guarantee *not* wanting this behaviour.

### Expected behaviour

I'd expect the tab bar to be hidden regardless of where in the navigation tree it is used, as seen in pre-2.0.

### Code sample

WIP

### What have you tried

Looking at `_renderTabBar` in `createBottomTabNavigator.js`, it seems that only the top-level options are ever looked at.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | /
| react-native          | 0.55.2
| react-navigation-tabs | 0.2.0
| node                  | /
| npm or yarn           | /

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by brentvatne** [comment]
oops I guess this issue template actually doesn't explain that, I confused it with react-navigation -- we should update it.

I'd double check that the behavior change described in https://reactnavigation.org/docs/en/navigation-options-resolution.html isn't the cause of what you're describing
