### ISSUE TITLE
tabBarVisible is ignored for nested scenes 

### ISSUE THREAD

**Issue by AndrewIngram** [react-navigation/react-navigation-tabs#19]
With react-navigation before 2.0, setting `tabBarVisible: false` at any level in the navigation tree would cause the tab bar to be hidden, this behaviour is now broken.

### Current behaviour

Setting `tabBarVisible: false` on any scene below the top level tab scenes will have no effect, making the setting largely useless because the top-level is probably the place where you can guarantee *not* wanting this behaviour.

### Expected behaviour

I'd expect the tab bar to be hidden regardless of where in the navigation tree it is used, as seen in pre-2.0.

### Code sample

https://snack.expo.io/@andrewingram/broken-tabbarvisible

Features 3 different usages of `tabBarVisible: false`, but only one of them works. In previous versions of React-Navigation, all 3 worked.

### What have you tried

Looking at `_renderTabBar` in `createBottomTabNavigator.js`, it seems that only the top-level options are ever looked at.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | /
| react-native          | 0.55.2
| react-navigation-tabs | 0.2.0
| node                  | /
| npm or yarn           | /

**Comment by brentvatne** [comment]
> It seems like this is part of the bigger change to how navigationOptions work, but seems like a pretty major regression.

A regression describes a behavior change that was unintentional so maybe the wording is wrong here. It was a very intentional change as you can see with the RFC.

I updated the Snack you provided to make `tabBarVisible` work as you expected: https://snack.expo.io/Sk7Go1WRM

Notice that in each case only the child screen of the tab navigator is aware that it's inside of a tab navigator. This is very intentional for the reasons I described in the RFC. 

It's also worth mentioning an alternative solution to the behavior in the "First" tab, where you want to hide the tab bar on nested screens. What you could do here instead (and what I'd recommend doing in order to avoid layout jumping when the tab disappears/re-appears) is put another stack on top of the tab bar and navigate to that. See the following Snack where I reworked the "First" tab accordingly: https://snack.expo.io/SkXH2J-CG

So, I'm still waiting to see cases where this causes legitimate problems that can't be expressed using the techniques I applied above. If someone can present these then I'd be happy to discuss how we can improve the API!

**Comment by AndrewIngram** [comment]
Also, I meant it to be a regression in the expected behavior of tabBarVisible, because I'm guessing the way I was doing it is how most people would have been using it.

**Comment by TheoGit** [comment]
@AndrewIngram I struggled with this issue but got it to work here's the link that helped:
https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-tab-navigator-contains-a-stack-and-you-want-to-hide-the-tab-bar-on-specific-screens
The tricky part was that instead of checking index (navigation.state.index > 0) the main navigation I had to do that in the nested navigation, the index on the main navigation never changed from 0.  I hope this helps.

**Comment by ShahidAli786** [comment]
@AndrewIngram Thanks!

**Comment by killabeeez** [comment]
Yes this example from snack works 
https://snack.expo.io/Sk7Go1WRM

StackA.navigationOptions = ({navigation})=>{
let { routeName } = navigation.state.routes[navigation.state.index];
let navigationOptions = {};
if (routeName === 'BrainStormScreen') {
navigationOptions.tabBarVisible = false;
}
return navigationOptions;
}

but on v1 version of react-navigation i was able to place **tabBarVisible** to **false** inside of screen that i wanted that kind of behavior :

export default class EventsScreen extends Component {
    static navigationOptions = {
    //Nav options can be defined as a function of the navigation prop:
      headerTitle: 'Events',
      headerStyle: { backgroundColor: 'white'},
      headerBackTitle: null,
      **tabBarVisible: false**,
  };
  ...
just wanted to ask is this possible on 2.0+ versions ?

**Comment by igor-shyrnin** [comment]
The decision, like this, is bad:
```
StackA.navigationOptions = ({navigation})=>{
let { routeName } = navigation.state.routes[navigation.state.index];
   let navigationOptions = {};
   if (routeName === 'BrainStormScreen') {
      navigationOptions.tabBarVisible = false;
   }
    return navigationOptions;
}
```
TabBar disappears before switching between screens and it looks twitched.

**Comment by dchhetri** [comment]
Second @igor-shyrnin statement. It would be nice if there was a smoother animation when hiding the tab-bar or providing a way for users to specify that. It looks unprofessional at the moment. But I'm just complaining right now. 


Also the recommended solution in the [docs](https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-tab-navigator-contains-a-stack-and-you-want-to-hide-the-tab-bar-on-specific-screens) is kind of wanky. It recommends us to create a stack navigator at the same level as our our Tab navigator. 

Although that may work, I don't think that should be the recommended solution because Its illogical to put a child screen at a higher level.

Logically, it doesn't always make sense to put a child screen of a screen listed inside tabnavigator at the same level as tabnavigator. Why should for example, my PostDetailScreen not live in the same navigator as my PostScreen? That poses potential problems on folder structure, hierarchy, and can be a cause of many confusions. It would be nice if someone can clear up the reasoning behind the recommended solution, I'm probably missing something here.

**Comment by tonmanayo** [comment]
I agree with @dchhetri that the animation when closing the tab from one screen to another looks really bad, some kind of animation would really help

**Comment by alvin-toffler** [comment]
Current solution:

```
const TabNavigator = createBottomTabNavigator(
  {
    ...
  },
  {
    initialRouteParams: { isTabBarChild: true },
  },
);

const setTabBarVisible = (tabBarVisible, navigation) => {
  let curr = navigation;
  while (!curr.getParam('isTabBarChild', false)) {
    curr = curr.dangerouslyGetParent();
  }
  const tabBarChild = curr;
  tabBarChild.setParams({ tabBarVisible });
};
```

**Comment by brentvatne** [comment]
this explains what to do: https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-tab-navigator-contains-a-stack-and-you-want-to-hide-the-tab-bar-on-specific-screens
