### ISSUE TITLE
Can't find variable React

### ISSUE THREAD

**Issue by daarkfish** [react-navigation/react-navigation-tabs#29]
### Current behaviour

got error when set a custom tabBarComponent for createBottomTabNavigator

### Expected behaviour

should have no error

### Code sample

```javascript
export const topNav =  createBottomTabNavigator({
    Pink: {
        screen: PinkScreen,  
    },
    Blue: {
        screen: BlueScreen
    }
},
{ 
    tabBarComponent:props => <TestTab {...props}/>
 
})
```

### Screenshots (if applicable)

<a href="https://ibb.co/byCvho"><img src="https://preview.ibb.co/nHDe8T/Simulator_Screen_Shot_i_Phone_6_2018_06_07_at_23_07_09.png" alt="Simulator_Screen_Shot_i_Phone_6_2018_06_07_at_23_07_09" border="0"></a><br />

### What have you tried

above code 
### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | ios 11.2
| react-native          | 0.55.4
| react-navigation-tabs | 0.5.1
| node                  | v8.9.4
| npm or yarn           | npm

**Comment by brentvatne** [comment]
you need to import React when you use JSX

**Comment by rkingon** [comment]
I really disagree with this. You should not need to `import` React in order to use `createBottomTabNavigator`. If `createBottomTabNavigator` has a dependency on React, it needs to import React itself.

1. This will drive a Linter crazy (no un-used variables)
2. It creates a fallible ecosystem

Are there any other options?

**Comment by fbartho** [comment]
@rkingon -- This isn't an issue caused by react-navigation/react-navigation-tabs, this is something to do with JSX itself.

The build environment (Babel?) is implicitly rewriting the `<TestTab {...props}/>` statement to something like `React.createElement(TestTab, …`

**Comment by rkingon** [comment]
@fbartho that actually makes sense. Total bummer!

Considering babel is using `React` behind the scenes, this solution may be "okay" (I don't love it).

https://www.npmjs.com/package/babel-plugin-provide-modules
```js
{
  "plugins": [
    ["provide-modules", {
      "react": "React"
    }]
  ]
}
```

**Comment by fbartho** [comment]
If you just import react into your source file, the problem will go away, for what it’s worth!

**Comment by rkingon** [comment]
@fbartho yes, it's what I am doing currently -- with an eslint ignore comment.

I was considering the provide module because if this is an issue with babel/jsx, it seems appropriate to have babel import React if it is going to using it. Sounds like this is going to be an issue in _any_ file that you are using JSX in without importing React already (not sure how common that is).
