### ISSUE TITLE
Tab navigation using createMaterialTopTabNavigator fails after swipe

### ISSUE THREAD

**Issue by asgerhallas** [react-navigation/react-navigation-tabs#94]
### How to reproduce

1. Use this setup https://snack.expo.io/@asgerhallas/creatematerialtoptabnavigator-fails-after-swipe.
2. Click the `Settings` tab.
3. Click the `Settings` tab again (this step, seems to be what makes it fail).
4. Swipe back to `Home`.
5. Click the `Settings` tab and observe that it does not work anymore.

### Current Behavior

I can not press the tab to return to a tab that I swiped away from - if I clicked it twice.

If I log `navigation.isFocused()` in tabBarOnPress, I can see that it remains `true` for the `Settings` tab even after I swiped away from it. And again, only if I have pressed the `Settings` tab twice.

### Expected Behavior

I expect to be able to navigate back to `Settings` by press.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.9
| react-native     | what snack.expo.io uses
| node             | what snack.expo.io uses
| npm or yarn      | what snack.expo.io uses
| mobile device | iPhone 7-10, iOS 12

**Comment by asgerhallas** [comment]
@eriveltonelias Sorry for the delay. I've updated the snack to 3.1.0, and the problem is still there.

**Comment by sijad** [comment]
I have same issue

**Comment by sijad** [comment]
I think react-navigation/react-navigation#4164 is related, @satya164 I think you need to pass a parameter to `isFocused()` otherwise it always [returns true](https://github.com/react-navigation/react-navigation-core/blob/44852e59a4bd524cc8fc44cc53d09c3a673fd903/src/getNavigation.js#L26).

also as you've changed `tabBarOnPress()` parameters (which was a breaking change BTW) I can not implement my own implement my own `jumpTo()` function because you only pass [navigation, defaultHandler](https://github.com/react-navigation/react-navigation-tabs/blob/e23142ec736cf7516123e2f9ba96f102045aae85/src/utils/createTabNavigator.js#L140) to `tabBarOnPress()` and it's not possible to find out which tab has been pressed on.

p.s. [types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-navigation/index.d.ts#L560-L565) need to be updated

**Comment by sijad** [comment]
sorry I was wrong, your implementation is current, I think this is the problem: https://github.com/react-native-community/react-native-tab-view/issues/525

I've tried to test new version but it's very slow on my device.

**Comment by RomuloDevelop** [comment]
I'm facing the same issue right now

**Comment by RomuloDevelop** [comment]
I updated to version 3.3.2 with react-native 0.57.8 and i don't noticed this error. I began to upgrade to version 0.59 and when i testing the app i notice this issue. I don't know if this has anything to do

**Comment by brentvatne** [comment]
you can use `react-navigation-tabs@2.0.0-alpha.0` - https://github.com/react-navigation/react-navigation-tabs/releases/tag/v2.0.0-alpha.0 - this should solve the issue.
